version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: aruba
    versions:
    - "> 0.14.2"
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
